export const icons = {
  'slide-1': require('../images/slide-1.png'),
  'slide-2': require('../images/slide-2.png'),
  'slide-3': require('../images/slide-3.png'),
  logo: require('../images/logo.png'),
  eye: require('../images/eye.png'),
  'eye-closed': require('../images/eye-closed.png'),
  facebook: require('../images/facebook.png'),
  google: require('../images/google.png'),
  apple: require('../images/apple.png'),
  research: require('../images/research.png'),
  finance: require('../images/finance.png'),
  avatar: require('../images/avatar.png'),
  indesign: require('../images/indesign.png'),
  council: require('../images/council.png'),
  cv: require('../images/cv.png'),
  cover: require('../images/cover.png'),
  button: require('../images/button.png'),
  pencil: require('../images/pencil.png'),
  dot: require('../images/3-dot.png'),
  calendar: require('../images/calendar.png'),
  plus: require('../images/plus-circle.png'),
  home: require('../images/Home.png'),
  vacancies: require('../images/Vacancies.png'),
  more: require('../images/more.png'),
  candidates: require('../images/candidates.png'),
  pluss: require('../images/plus.png'),
  person: require('../images/person.png'),
  pencl: require('../images/pencl.png'),
  delete: require('../images/delete.png'),
  Home: require('../images/home-focused.png'),
  Candidate: require('../images/candidate-focused.png'),
  Vacanciie: require('../images/vacancie-focused.png'),
  More: require('../images/more-focused.png'),
};

export type IconTypes = keyof typeof icons;
